### ISSUE TITLE
 Compatibility issues with newer versions

### ISSUE THREAD

**Issue by ummmme** [manuelernestog/joplin-minimalist-light-theme#1]
Compatibility issues with newer versions 2.8.8+, like 2.10.18；white screen while applying this theme

**Comment by manuelernestog** [comment]
Hi @ummmme thanks for the feedback man, sadly I'm not working with Joplin right now and have a lot of work how to support this repository :(

I'm going to archive this repo

Thanks for the feedback again. Regards
